### ISSUE TITLE
[Feature/Idea]: Support Environment

### ISSUE THREAD

**Issue by Michel73** [vedantmgoyal9/setup-wsl2#2]
### What would you like to see changed/added?

Can't use variables given by the **env** entry.
Following does not show the given TEST_ENV variable:
```
- uses: vedantmgoyal9/setup-wsl2@main
- name: run wsl demo
    env:
      TEST_ENV: Foobar
    run: |
      env
    shell: wsl-run {0}
```
